# Site settings
title: HongSheng の Blog
description: 最爱刘宝宝
baseurl: "" 
#change the baseurl to "" if you are using it as your user GitHub Pages
url: "https://wanghongsheng9527.github.io"  


# GitHub User settings
username: 三生红绳
github_username: wanghongsheng9527
user_description: user_description
user_title: Whs_title
email: wanghongsheng9527@163.com

# Blog Author settings
author:
  name: Hongsheng Wang  
  picture:  https://whs-guli-file.oss-cn-beijing.aliyuncs.com/images/life/athor.jpg      
  email:  wanghongsheng9527@163.com         
  description:  为了未来奋斗，加油！王大头！   
  twitter:
  facebook:
  github: https://github.com/wanghongsheng9527         
  linkedin:
  clustrmap:      


# markdown
markdown: kramdown
  
kramdown:
 footnote_nr: 1
 entity_output: as_char
 # Jekyll 3 and GitHub Pages now only support rouge for syntax highlighting
 syntax_highlighter: rouge
 syntax_highlighter_opts:
  # Use existing pygments syntax highlighting css
  css_class: 'highlight'
 span:
  line_numbers: false
 block:
  line_numbers: true
  start_line: 1
 
highlighter: rouge
    
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  
permalink: none

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      toc: true
      mathjax: true
      mermaid: false
      highlight: false
      numbering: true
      status: Completed
      protected: false
      commentable: true
      rss: true
      numbering: true

exclude:
 - LICENSE.md
 - README.md
 - "*.cdf"
 - "*.nb"
 - "*.bk"
 - "*.draft.md"
